
const mongoose = require('mongoose');

const AccountSchema = new mongoose.Schema({
    id: String,
    name: String,
    number: String,
    type: String,
    balance: Number,
    isActive: Boolean,
    description: String,
    parentId: String,
    currency: String,
    bankAccountNumber: String,
    routingNumber: String,
    taxLineMapping: String,
});

const ItemSchema = new mongoose.Schema({
    id: String,
    name: String,
    type: String,
    isActive: Boolean,
    description: String,
    purchaseDescription: String,
    salesPrice: Number,
    cost: Number,
    incomeAccountId: String,
    cogsAccountId: String,
    assetAccountId: String,
    onHand: Number,
    reorderPoint: Number,
    taxCode: String,
    customFieldValues: Object,
});

const CustomerSchema = new mongoose.Schema({
    id: String,
    name: String,
    companyName: String,
    email: String,
    phone: String,
    balance: Number,
    address: String,
    isActive: Boolean,
    jobs: Array,
    notes: Array,
    contacts: Array,
    customFieldValues: Object,
    Title: String,
    GivenName: String,
    MiddleName: String,
    FamilyName: String,
    Suffix: String,
    DisplayName: String,
    PrimaryPhone: Object,
    AlternatePhone: Object,
    Mobile: Object,
    Fax: Object,
    PrimaryEmailAddr: Object,
    WebAddr: Object,
    BillAddr: Object,
    ShipAddr: Object,
    TaxIdentifier: String,
    TermsRef: Object,
    PreferredPaymentMethodRef: Object,
    CurrencyRef: Object,
}, { strict: false });

const VendorSchema = new mongoose.Schema({
    id: String,
    name: String,
    companyName: String,
    phone: String,
    email: String,
    balance: Number,
    address: String,
    isActive: Boolean,
    eligibleFor1099: Boolean,
    contacts: Array,
    preFillAccounts: Array,
    customFieldValues: Object,
    notes: Array,
    Title: String,
    GivenName: String,
    MiddleName: String,
    FamilyName: String,
    Suffix: String,
    DisplayName: String,
    PrintOnCheckName: String,
    PrimaryPhone: Object,
    AlternatePhone: Object,
    Mobile: Object,
    Fax: Object,
    PrimaryEmailAddr: Object,
    WebAddr: Object,
    BillAddr: Object,
    ShipAddr: Object,
    TaxIdentifier: String,
    Vendor1099: Boolean,
    BillWithholdingTax: Boolean,
    OpenBalance: Number,
    OpenBalanceDate: String,
    vendorType: String,
    billingRateLevel: String,
    TermsRef: Object,
    PreferredPaymentMethodRef: Object,
    CurrencyRef: Object,
    CreditLimit: Number,
    vendorAccountNo: String,
}, { strict: false });

const TransactionSchema = new mongoose.Schema({
    id: String,
    type: { type: String },
    refNo: String,
    date: String,
    dueDate: String,
    entityId: String,
    items: Array,
    total: Number,
    status: String,
    bankAccountId: String,
    depositToId: String,
    transferFromId: String,
    transferToId: String,
    paymentMethod: String,
    appliedCreditIds: Array,
    purchaseOrderId: String,
});

const AppStoreSchema = new mongoose.Schema({
    accounts: [AccountSchema],
    customers: [CustomerSchema],
    vendors: [VendorSchema],
    employees: Array,
    transactions: [TransactionSchema],
    timeEntries: Array,
    items: [ItemSchema],
    priceLevels: Array,
    salesTaxCodes: Array,
    paymentMethods: [String],
    customerMessages: [String],
    terms: Array,
    budgets: Array,
    memorizedReports: Array,
    liabilities: Array,
    leads: Array,
    customFields: Array,
    companyConfig: Object,
    classes: Array,
    salesReps: Array,
    customerTypes: Array,
    vendorTypes: Array,
    shipVia: Array,
    shortcuts: Array,
    shortcutGroups: Array,
}, { timestamps: true, strict: false });

module.exports = mongoose.model('AppStore', AppStoreSchema);
