const mongoose = require('mongoose');

const TransactionItemSchema = new mongoose.Schema({
    id: String,
    itemId: String,
    description: String,
    quantity: Number,
    rate: Number,
    amount: Number,
    tax: Boolean,
    customerId: String,
    isBillable: Boolean,
    classId: String,
    exchangeRate: Number,
    userId: String,
    accountId: String,
    creditCategoryId: String,
    receivedQuantity: { type: Number, default: 0 },
    isClosed: { type: Boolean, default: false },
});

const TransactionSchema = new mongoose.Schema({
    id: { type: String, required: true, unique: true },
    type: { type: String, required: true },
    userId: { type: String, required: true },
    companyId: { type: String, required: true },
    refNo: String,
    date: { type: String, required: true },
    dueDate: String,
    entityId: String,
    customerId: String,
    vendorId: String,
    employeeId: String,
    items: [TransactionItemSchema],
    total: { type: Number, required: true },
    status: String,
    bankAccountId: String,
    depositToId: String,
    transferFromId: String,
    transferToId: String,
    paymentMethod: String,
    appliedCreditIds: [String],
    purchaseOrderId: String,
    customerInvoiceNo: String,
    expectedDate: String,
    vendorMessage: String,
    itemReceiptId: String,
    lotNumber: String,
    classId: String,
    salesRepId: String,
    shipVia: String,
    memo: String,
    exchangeRate: Number,
    homeAmount: Number,
    isChangeOrder: Boolean,
    subtotal: Number,
    taxAmount: Number,
    trackingNo: String,
    shipDate: String,
    fob: String,
    email: String,
    cc: String,
    bcc: String,
    paymentOptions: [String],
    memoOnStatement: String,
    attachments: [Object],
    deposit: Number,
    taxItemId: String,
    terms: String,
    BillAddr: Object,
    ShipAddr: Object,
    shippingDetails: {
        shipmentCost: Number,
        innerPackDimensions: { length: Number, width: Number, height: Number, unit: String },
        outerBoxDimensions: { length: Number, width: Number, height: Number, unit: String },
        masterCartonDimensions: { length: Number, width: Number, height: Number, unit: String }
    },
    discountAmount: Number,
    discountPercentage: Number,
    isDiscountPercentage: Boolean,
    lateFee: Number,
    tip: Number,
    internalNotes: String,
    location: String,
    taxRate: Number
}, { timestamps: true });

module.exports = mongoose.model('Transaction', TransactionSchema);
